In [13]:
import osmnx as ox

# 1. 设置 osmnx 的一些基础配置（可选）
ox.settings.use_cache = True        # 缓存请求，重复运行会更快
ox.settings.log_console = True      # 在控制台打印日志，方便看进度

# 2. 定义研究区域名称（内罗毕）
place_name = "Nairobi, Kenya"

# 3. 下载道路网络
# network_type:
#   'drive'  : 可行驶道路（默认适合交通分析）
#   'all'    : 所有道路，包括小路、步道
#   'walk'   : 行人可走
#   'bike'   : 自行车可走
G = ox.graph_from_place(place_name, network_type="all")

print(G)

MultiDiGraph with 73815 nodes and 173873 edges

In [14]:
# 将图转为边（即道路）和点（路口）的 GeoDataFrame
gdf_nodes, gdf_edges = ox.graph_to_gdfs(G)

print(gdf_edges.head())

                              osmid        highway                name  \
u        v          key
29780021 280701730  0     663223989      secondary  Airport South Road
         9764595543 0    1063322693  motorway_link                 NaN
29780039 7181149132 0       4685092      secondary  Airport South Road
         30695893   0    1112388311      secondary                 NaN
29780051 4865507507 0       4685092      secondary  Airport South Road

                         oneway   ref reversed      length  \
u        v          key
29780021 280701730  0      True  B10E    False  201.712778
         9764595543 0      True   NaN    False  395.438214
29780039 7181149132 0      True  B10E    False  329.147867
         30695893   0      True  B10E    False   69.913352
29780051 4865507507 0      True  B10E    False  488.481098

                                                                  geometry  \
u        v          key
29780021 280701730  0    LINESTRING (36.90372 -1.34736, 36.90364 -1.347...
         9764595543 0    LINESTRING (36.90372 -1.34736, 36.90362 -1.347...
29780039 7181149132 0    LINESTRING (36.91442 -1.34465, 36.91427 -1.344...
         30695893   0    LINESTRING (36.91442 -1.34465, 36.9143 -1.3446...
29780051 4865507507 0    LINESTRING (36.90921 -1.34792, 36.90851 -1.348...

                           junction lanes maxspeed service access bridge  \
u        v          key
29780021 280701730  0           NaN   NaN      NaN     NaN    NaN    NaN
         9764595543 0           NaN   NaN      NaN     NaN    NaN    NaN
29780039 7181149132 0           NaN   NaN      NaN     NaN    NaN    NaN
         30695893   0    roundabout     2      NaN     NaN    NaN    NaN
29780051 4865507507 0           NaN   NaN      NaN     NaN    NaN    NaN

                        tunnel width
u        v          key
29780021 280701730  0      NaN   NaN
         9764595543 0      NaN   NaN
29780039 7181149132 0      NaN   NaN
         30695893   0      NaN   NaN
29780051 4865507507 0      NaN   NaN

In [15]:
gdf_edges

                                  osmid        highway                name  \
u           v           key
29780021    280701730   0     663223989      secondary  Airport South Road
            9764595543  0    1063322693  motorway_link                 NaN
29780039    7181149132  0       4685092      secondary  Airport South Road
            30695893    0    1112388311      secondary                 NaN
29780051    4865507507  0       4685092      secondary  Airport South Road
...                                 ...            ...                 ...
13337336553 13337336562 1    1454302219        service                 NaN
            280246932   0      42121150    residential      Ridgeway Drive
13337336562 13337336553 0      42121150    residential      Ridgeway Drive
                        1    1454302219        service                 NaN
            8573928373  0      42121150    residential      Ridgeway Drive

                             oneway   ref reversed      length  \
u           v           key
29780021    280701730   0      True  B10E    False  201.712778
            9764595543  0      True   NaN    False  395.438214
29780039    7181149132  0      True  B10E    False  329.147867
            30695893    0      True  B10E    False   69.913352
29780051    4865507507  0      True  B10E    False  488.481098
...                             ...   ...      ...         ...
13337336553 13337336562 1     False   NaN     True   67.774240
            280246932   0     False   NaN    False   33.375175
13337336562 13337336553 0     False   NaN    False   22.281035
                        1     False   NaN    False   67.774240
            8573928373  0     False   NaN     True   46.538600

                                                                      geometry  \
u           v           key
29780021    280701730   0    LINESTRING (36.90372 -1.34736, 36.90364 -1.347...
            9764595543  0    LINESTRING (36.90372 -1.34736, 36.90362 -1.347...
29780039    7181149132  0    LINESTRING (36.91442 -1.34465, 36.91427 -1.344...
            30695893    0    LINESTRING (36.91442 -1.34465, 36.9143 -1.3446...
29780051    4865507507  0    LINESTRING (36.90921 -1.34792, 36.90851 -1.348...
...                                                                        ...
13337336553 13337336562 1    LINESTRING (36.8412 -1.22503, 36.8413 -1.22497...
            280246932   0    LINESTRING (36.8412 -1.22503, 36.84127 -1.2252...
13337336562 13337336553 0     LINESTRING (36.84112 -1.22485, 36.8412 -1.22503)
                        1    LINESTRING (36.84112 -1.22485, 36.84125 -1.224...
            8573928373  0    LINESTRING (36.84112 -1.22485, 36.84106 -1.224...

                               junction lanes maxspeed service access bridge  \
u           v           key
29780021    280701730   0           NaN   NaN      NaN     NaN    NaN    NaN
            9764595543  0           NaN   NaN      NaN     NaN    NaN    NaN
29780039    7181149132  0           NaN   NaN      NaN     NaN    NaN    NaN
            30695893    0    roundabout     2      NaN     NaN    NaN    NaN
29780051    4865507507  0           NaN   NaN      NaN     NaN    NaN    NaN
...                                 ...   ...      ...     ...    ...    ...
13337336553 13337336562 1           NaN   NaN      NaN     NaN    NaN    NaN
            280246932   0           NaN   NaN      NaN     NaN    NaN    NaN
13337336562 13337336553 0           NaN   NaN      NaN     NaN    NaN    NaN
                        1           NaN   NaN      NaN     NaN    NaN    NaN
            8573928373  0           NaN   NaN      NaN     NaN    NaN    NaN

                            tunnel width
u           v           key
29780021    280701730   0      NaN   NaN
            9764595543  0      NaN   NaN
29780039    7181149132  0      NaN   NaN
            30695893    0      NaN   NaN
29780051    4865507507  0      NaN   NaN
...                            ...   ...
13337336553 13337336562 1      NaN   NaN
            280246932   0      NaN   NaN
13337336562 13337336553 0      NaN   NaN
                        1      NaN   NaN
            8573928373  0      NaN   NaN

[173873 rows x 16 columns]

In [9]:
# reset_index(inplace=True, drop=True)  # 重置索引
gdf_edges.reset_index(inplace=True)  # 重置索引
gdf_edges.reset_index(inplace=True, drop=True)  # 重置索引

In [10]:
gdf_edges

,u,v,key,osmid,highway,name,oneway,ref,reversed,length,geometry,junction,lanes,maxspeed,bridge,access,tunnel,width
0,29780021,280701730,0,663223989,secondary,Airport South Road,True,B10E,False,201.712778,"LINESTRING (36.90372 -1.34736, 36.90364 -1.347...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,29780021,9764595543,0,1063322693,motorway_link,NaN,True,NaN,False,395.438214,"LINESTRING (36.90372 -1.34736, 36.90362 -1.347...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29780039,7181149132,0,4685092,secondary,Airport South Road,True,B10E,False,329.147867,"LINESTRING (36.91442 -1.34465, 36.91427 -1.344...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,29780039,30695893,0,1112388311,secondary,NaN,True,B10E,False,69.913352,"LINESTRING (36.91442 -1.34465, 36.9143 -1.3446...",roundabout,2,NaN,NaN,NaN,NaN,NaN
4,29780051,29780021,0,"[4685092, 663223989]",secondary,Airport South Road,True,B10E,False,631.230873,"LINESTRING (36.90921 -1.34792, 36.90851 -1.348...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88830,13337336550,13337336551,0,1454302217,residential,NaN,False,NaN,True,58.815298,"LINESTRING (36.84783 -1.23011, 36.8476 -1.22963)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
88831,13337336551,1283152148,0,113040683,residential,NaN,False,NaN,True,94.551062,"LINESTRING (36.8476 -1.22963, 36.84689 -1.23009)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
88832,13337336551,13337336550,0,1454302217,residential,NaN,False,NaN,False,58.815298,"LINESTRING (36.8476 -1.22963, 36.84783 -1.23011)",NaN,NaN,NaN,NaN,NaN,NaN,NaN
88833,13337336551,6158863295,0,113040683,residential,NaN,False,NaN,False,99.395976,"LINESTRING (36.8476 -1.22963, 36.8483 -1.22923...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
88834,13337336552,5348847742,0,"[554225136, 1454302218]",residential,NaN,False,NaN,"[False, True]",94.794967,"LINESTRING (36.84134 -1.22645, 36.84145 -1.226...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
# 处理 highway 字段：如果是列表，只取第一个元素
# Handle cases where 'highway' is a list by taking the first element to fix "unhashable type: 'list'"
gdf_edges['highway'] = gdf_edges['highway'].apply(lambda x: x[0] if isinstance(x, list) else x)
gdf_edges['reversed'] = gdf_edges['reversed'].apply(lambda x: x[0] if isinstance(x, list) else x)
gdf_edges['osmid'] = gdf_edges['osmid'].apply(lambda x: x[0] if isinstance(x, list) else x)

In [16]:
# export to gpkg
gdf_edges.to_file("Nairobi_road_edges.gpkg", driver='GPKG')
# export to file if needed
gdf_nodes.to_file("Nairobi_road_nodes.gpkg", driver='GPKG')

In [ ]:
# add elevation data to gdf_edges